Parameter Q(S,A) /
  Event_Driven_Automation.B_Managed_Container 0.0287
  Event_Driven_Automation.C_Serverless_API 0.4159
  Event_Driven_Automation.E_Event_Driven_Serverless 0.5377
  Event_Driven_Automation.D_High_Scale_Microservices 0.712
  Event_Driven_Automation.A_Traditional_Web 0.9985
  Growing_SaaS.B_Managed_Container 0.0
  Growing_SaaS.C_Serverless_API 0.51
  Growing_SaaS.E_Event_Driven_Serverless 0.6487
  Growing_SaaS.D_High_Scale_Microservices 0.6576
  Growing_SaaS.A_Traditional_Web 0.988
  High_Traffic_Platform.B_Managed_Container 0.0
  High_Traffic_Platform.D_High_Scale_Microservices 0.5132
  High_Traffic_Platform.C_Serverless_API 0.5176
  High_Traffic_Platform.E_Event_Driven_Serverless 0.6815
  High_Traffic_Platform.A_Traditional_Web 0.8918
  Low_Budget_MVP.B_Managed_Container 0.0253
  Low_Budget_MVP.C_Serverless_API 0.4349
  Low_Budget_MVP.E_Event_Driven_Serverless 0.5563
  Low_Budget_MVP.D_High_Scale_Microservices 0.7361
  Low_Budget_MVP.A_Traditional_Web 0.9912
  Security_Sensitive_Fintech.B_Managed_Container 0.0068
  Security_Sensitive_Fintech.C_Serverless_API 0.4181
  Security_Sensitive_Fintech.E_Event_Driven_Serverless 0.5468
  Security_Sensitive_Fintech.D_High_Scale_Microservices 0.6516
  Security_Sensitive_Fintech.A_Traditional_Web 1.0
/;

